import numpy as np
import pytest
import scipy.io

from pygridfit import GridFit, TiledGridFit

# --- Octave reference data (deterministic synthetic trig surface) ---
# Generated by dev/generate_references.m using GNU Octave + gridfit.m
_synth = scipy.io.loadmat("./tests/data/synth_references.mat")
_synth_x = _synth["synth_x"].flatten()
_synth_y = _synth["synth_y"].flatten()
_synth_z = _synth["synth_z"].flatten()
_synth_xnodes = _synth["synth_xnodes"].flatten()
_synth_ynodes = _synth["synth_ynodes"].flatten()

# Original bluff dataset (single-combo legacy test)
_bluff = scipy.io.loadmat("./tests/data/bluff_data.mat")


INTERPS = ["triangle", "bilinear", "nearest"]
REGULARIZERS = ["gradient", "diffusion", "springs"]


@pytest.mark.parametrize("interp", INTERPS)
@pytest.mark.parametrize("regularizer", REGULARIZERS)
def test_gridfit_vs_octave(interp, regularizer):
    """Every interp x regularizer combo must match Octave reference (normal solver)."""
    key = f"{interp}_{regularizer}_normal"
    ref = _synth["results"][key][0, 0]

    gf = GridFit(
        _synth_x, _synth_y, _synth_z,
        xnodes=_synth_xnodes, ynodes=_synth_ynodes,
        smoothness=1, interp=interp, regularizer=regularizer,
        solver="normal", extend="never",
    ).fit()

    np.testing.assert_allclose(gf.zgrid, ref, atol=1e-10)


@pytest.mark.parametrize("interp,regularizer", [
    ("triangle", "gradient"),
    ("bilinear", "diffusion"),
    ("nearest", "springs"),
])
def test_gridfit_anisotropic_vs_octave(interp, regularizer):
    """Anisotropic smoothness [1, 2] must match Octave reference."""
    key = f"aniso_{interp}_{regularizer}_normal"
    ref = _synth["results"][key][0, 0]

    gf = GridFit(
        _synth_x, _synth_y, _synth_z,
        xnodes=_synth_xnodes, ynodes=_synth_ynodes,
        smoothness=[1, 2], interp=interp, regularizer=regularizer,
        solver="normal", extend="never",
    ).fit()

    np.testing.assert_allclose(gf.zgrid, ref, atol=1e-10)


@pytest.mark.parametrize("interp", INTERPS)
@pytest.mark.parametrize("regularizer", REGULARIZERS)
def test_gridfit_lsqr_vs_normal(interp, regularizer):
    """lsqr solver must agree with normal solver (both solve the same system)."""
    kwargs = dict(
        xnodes=_synth_xnodes, ynodes=_synth_ynodes,
        smoothness=1, interp=interp, regularizer=regularizer,
        extend="never",
    )
    gn = GridFit(_synth_x, _synth_y, _synth_z, solver="normal", **kwargs).fit()
    gl = GridFit(_synth_x, _synth_y, _synth_z, solver="lsqr", **kwargs).fit()

    np.testing.assert_allclose(gl.zgrid, gn.zgrid, atol=1e-9)


def test_gridfit_bluff():
    """Legacy test: bluff dataset with triangle/gradient/normal."""
    x = _bluff["x"].flatten()
    y = _bluff["y"].flatten()
    z = _bluff["z"].flatten()
    gx = np.arange(0, 268, 4)
    gy = np.arange(0, 404, 4)

    gf = GridFit(
        x, y, z,
        xnodes=gx, ynodes=gy,
        smoothness=1, interp="triangle", regularizer="gradient",
        solver="normal",
    ).fit()

    assert np.allclose(gf.zgrid, _bluff["g"])


def test_tiled_gridfit_sparse_tiles_preserve_existing_blends():
    xnodes = np.arange(0, 6, 1)
    ynodes = np.arange(0, 3, 1)

    xv, yv = np.meshgrid([0, 1, 2], [0, 1, 2])
    x = xv.ravel()
    y = yv.ravel()
    z = x + y

    tg = TiledGridFit(
        x,
        y,
        z,
        xnodes=xnodes,
        ynodes=ynodes,
        smoothness=0.1,
        tilesize=4,
        overlap=0.5,
        regularizer="gradient",
        extend="never",
        interp="triangle",
        solver="normal",
    ).fit()

    assert np.all(np.isfinite(tg.zgrid[:, :3]))
    assert np.all(np.isnan(tg.zgrid[:, 3:]))


def test_tiled_gridfit_supports_zero_overlap():
    xnodes = np.linspace(0, 4, 5)
    ynodes = np.linspace(0, 4, 5)

    xv, yv = np.meshgrid(xnodes, ynodes)
    x_base = xv.ravel()
    y_base = yv.ravel()
    z_base = x_base + 2 * y_base

    reps = 4
    x = np.repeat(x_base, reps)
    y = np.repeat(y_base, reps)
    z = np.repeat(z_base, reps)

    baseline = GridFit(
        x,
        y,
        z,
        xnodes=xnodes,
        ynodes=ynodes,
        smoothness=0.5,
        extend="never",
        interp="triangle",
        regularizer="gradient",
        solver="normal",
    ).fit().zgrid

    tiled = TiledGridFit(
        x,
        y,
        z,
        xnodes=xnodes,
        ynodes=ynodes,
        smoothness=0.5,
        tilesize=3,
        overlap=0.0,
        extend="never",
        interp="triangle",
        regularizer="gradient",
        solver="normal",
    ).fit().zgrid

    assert np.allclose(tiled, baseline)
